/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributesRouteImport } from './routes/attributes'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StorefrontRouteImport } from './routes/storefront'
import { Route as SubCategoriesRouteImport } from './routes/sub-categories'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as CmsIndexRouteImport } from './routes/cms.index'
import { Route as CmsContentIdRouteImport } from './routes/cms.$contentId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryAddStockRouteImport } from './routes/inventory.add-stock'
import { Route as InventoryAdjustmentRouteImport } from './routes/inventory.adjustment'
import { Route as InventoryHistoryRouteImport } from './routes/inventory.history'
import { Route as InventoryLowStockRouteImport } from './routes/inventory.low-stock'
import { Route as InventoryMovementsRouteImport } from './routes/inventory.movements'
import { Route as InventoryOutOfStockRouteImport } from './routes/inventory.out-of-stock'
import { Route as InventoryStockRouteImport } from './routes/inventory.stock'
import { Route as InventoryTransferRouteImport } from './routes/inventory.transfer'
import { Route as MasterBatchesRouteImport } from './routes/master.batches'
import { Route as MasterCommissionsRouteImport } from './routes/master.commissions'
import { Route as MasterLocationsRouteImport } from './routes/master.locations'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformOffersRouteImport } from './routes/platform.offers'
import { Route as PlatformOperationsRouteImport } from './routes/platform.operations'
import { Route as PlatformPaymentsRouteImport } from './routes/platform.payments'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as ProductionProductionIdRouteImport } from './routes/production.$productionId'
import { Route as ProductionBatchesRouteImport } from './routes/production.batches'
import { Route as ProductionHistoryRouteImport } from './routes/production.history'
import { Route as ProductionListRouteImport } from './routes/production.list'
import { Route as ProductionNewRouteImport } from './routes/production.new'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ProductsNewRouteImport } from './routes/products.new'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ReportsOrdersRouteImport } from './routes/reports.orders'
import { Route as ReportsProductionRouteImport } from './routes/reports.production'
import { Route as ReportsReturnsRouteImport } from './routes/reports.returns'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsSettlementsRouteImport } from './routes/reports.settlements'
import { Route as ReportsTransactionsRouteImport } from './routes/reports.transactions'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'
import { Route as VendorsActivityRouteImport } from './routes/vendors.activity'
import { Route as VendorsListRouteImport } from './routes/vendors.list'
import { Route as VendorsOrdersRouteImport } from './routes/vendors.orders'
import { Route as VendorsPaymentsRouteImport } from './routes/vendors.payments'
import { Route as VendorsPerformanceRouteImport } from './routes/vendors.performance'
import { Route as VendorsProductsRouteImport } from './routes/vendors.products'
import { Route as VendorsRegistrationsRouteImport } from './routes/vendors.registrations'
import { Route as VendorsReturnsRouteImport } from './routes/vendors.returns'
import { Route as VendorsSettlementsRouteImport } from './routes/vendors.settlements'
import { Route as VendorsTransactionsRouteImport } from './routes/vendors.transactions'
import { Route as MasterKindItemIdRouteImport } from './routes/master.$kind.$itemId'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products.$productId.index'
import { Route as ProductsProductIdEditRouteImport } from './routes/products.$productId.edit'
import { Route as SettingsNotificationsIndexRouteImport } from './routes/settings.notifications.index'
import { Route as SettingsNotificationsNotificationIdRouteImport } from './routes/settings.notifications.$notificationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributesRoute = AttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRoute = StorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const SubCategoriesRoute = SubCategoriesRouteImport.update({
  id: '/sub-categories',
  path: '/sub-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CmsRoute,
} as any)
const CmsContentIdRoute = CmsContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => CmsRoute,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryAddStockRoute = InventoryAddStockRouteImport.update({
  id: '/add-stock',
  path: '/add-stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryAdjustmentRoute = InventoryAdjustmentRouteImport.update({
  id: '/adjustment',
  path: '/adjustment',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryHistoryRoute = InventoryHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryLowStockRoute = InventoryLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryMovementsRoute = InventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryOutOfStockRoute = InventoryOutOfStockRouteImport.update({
  id: '/out-of-stock',
  path: '/out-of-stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryTransferRoute = InventoryTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => InventoryRoute,
} as any)
const MasterBatchesRoute = MasterBatchesRouteImport.update({
  id: '/master/batches',
  path: '/master/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterCommissionsRoute = MasterCommissionsRouteImport.update({
  id: '/master/commissions',
  path: '/master/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterLocationsRoute = MasterLocationsRouteImport.update({
  id: '/master/locations',
  path: '/master/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOffersRoute = PlatformOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOperationsRoute = PlatformOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPaymentsRoute = PlatformPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PlatformRoute,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionProductionIdRoute = ProductionProductionIdRouteImport.update({
  id: '/$productionId',
  path: '/$productionId',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionBatchesRoute = ProductionBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionHistoryRoute = ProductionHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionListRoute = ProductionListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionNewRoute = ProductionNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsOrdersRoute = ReportsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsProductionRoute = ReportsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsReturnsRoute = ReportsReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSettlementsRoute = ReportsSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsTransactionsRoute = ReportsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ReportsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/$vendorId',
  path: '/$vendorId',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsActivityRoute = VendorsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsListRoute = VendorsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsOrdersRoute = VendorsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsPaymentsRoute = VendorsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsPerformanceRoute = VendorsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsProductsRoute = VendorsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsRegistrationsRoute = VendorsRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsReturnsRoute = VendorsReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsSettlementsRoute = VendorsSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => VendorsRoute,
} as any)
const VendorsTransactionsRoute = VendorsTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => VendorsRoute,
} as any)
const MasterKindItemIdRoute = MasterKindItemIdRouteImport.update({
  id: '/master/$kind/$itemId',
  path: '/master/$kind/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsProductIdRoute,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsProductIdRoute,
} as any)
const SettingsNotificationsIndexRoute =
  SettingsNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsNotificationsRoute,
  } as any)
const SettingsNotificationsNotificationIdRoute =
  SettingsNotificationsNotificationIdRouteImport.update({
    id: '/$notificationId',
    path: '/$notificationId',
    getParentRoute: () => SettingsNotificationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/cms': typeof CmsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/storefront': typeof StorefrontRoute
  '/sub-categories': typeof SubCategoriesRoute
  '/taxes': typeof TaxesRoute
  '/units': typeof UnitsRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/warehouses': typeof WarehousesRoute
  '/cms/$contentId': typeof CmsContentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/inventory/add-stock': typeof InventoryAddStockRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/out-of-stock': typeof InventoryOutOfStockRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/master/batches': typeof MasterBatchesRoute
  '/master/commissions': typeof MasterCommissionsRoute
  '/master/locations': typeof MasterLocationsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/platform/offers': typeof PlatformOffersRoute
  '/platform/operations': typeof PlatformOperationsRoute
  '/platform/payments': typeof PlatformPaymentsRoute
  '/production/$productionId': typeof ProductionProductionIdRoute
  '/production/batches': typeof ProductionBatchesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/list': typeof ProductionListRoute
  '/production/new': typeof ProductionNewRoute
  '/products/$productId': typeof ProductsProductIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/orders': typeof ReportsOrdersRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/returns': typeof ReportsReturnsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/transactions': typeof ReportsTransactionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRouteWithChildren
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/activity': typeof VendorsActivityRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/orders': typeof VendorsOrdersRoute
  '/vendors/payments': typeof VendorsPaymentsRoute
  '/vendors/performance': typeof VendorsPerformanceRoute
  '/vendors/products': typeof VendorsProductsRoute
  '/vendors/registrations': typeof VendorsRegistrationsRoute
  '/vendors/returns': typeof VendorsReturnsRoute
  '/vendors/settlements': typeof VendorsSettlementsRoute
  '/vendors/transactions': typeof VendorsTransactionsRoute
  '/cms/': typeof CmsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/master/$kind/$itemId': typeof MasterKindItemIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/settings/notifications/$notificationId': typeof SettingsNotificationsNotificationIdRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/storefront': typeof StorefrontRoute
  '/sub-categories': typeof SubCategoriesRoute
  '/taxes': typeof TaxesRoute
  '/units': typeof UnitsRoute
  '/warehouses': typeof WarehousesRoute
  '/cms/$contentId': typeof CmsContentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/inventory/add-stock': typeof InventoryAddStockRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/out-of-stock': typeof InventoryOutOfStockRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/master/batches': typeof MasterBatchesRoute
  '/master/commissions': typeof MasterCommissionsRoute
  '/master/locations': typeof MasterLocationsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/platform/offers': typeof PlatformOffersRoute
  '/platform/operations': typeof PlatformOperationsRoute
  '/platform/payments': typeof PlatformPaymentsRoute
  '/production/$productionId': typeof ProductionProductionIdRoute
  '/production/batches': typeof ProductionBatchesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/list': typeof ProductionListRoute
  '/production/new': typeof ProductionNewRoute
  '/products/new': typeof ProductsNewRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/orders': typeof ReportsOrdersRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/returns': typeof ReportsReturnsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/transactions': typeof ReportsTransactionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/activity': typeof VendorsActivityRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/orders': typeof VendorsOrdersRoute
  '/vendors/payments': typeof VendorsPaymentsRoute
  '/vendors/performance': typeof VendorsPerformanceRoute
  '/vendors/products': typeof VendorsProductsRoute
  '/vendors/registrations': typeof VendorsRegistrationsRoute
  '/vendors/returns': typeof VendorsReturnsRoute
  '/vendors/settlements': typeof VendorsSettlementsRoute
  '/vendors/transactions': typeof VendorsTransactionsRoute
  '/cms': typeof CmsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/production': typeof ProductionIndexRoute
  '/products': typeof ProductsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/master/$kind/$itemId': typeof MasterKindItemIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/settings/notifications/$notificationId': typeof SettingsNotificationsNotificationIdRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributes': typeof AttributesRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/cms': typeof CmsRouteWithChildren
  '/customers': typeof CustomersRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/storefront': typeof StorefrontRoute
  '/sub-categories': typeof SubCategoriesRoute
  '/taxes': typeof TaxesRoute
  '/units': typeof UnitsRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/warehouses': typeof WarehousesRoute
  '/cms/$contentId': typeof CmsContentIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/inventory/add-stock': typeof InventoryAddStockRoute
  '/inventory/adjustment': typeof InventoryAdjustmentRoute
  '/inventory/history': typeof InventoryHistoryRoute
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/movements': typeof InventoryMovementsRoute
  '/inventory/out-of-stock': typeof InventoryOutOfStockRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/master/batches': typeof MasterBatchesRoute
  '/master/commissions': typeof MasterCommissionsRoute
  '/master/locations': typeof MasterLocationsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/platform/offers': typeof PlatformOffersRoute
  '/platform/operations': typeof PlatformOperationsRoute
  '/platform/payments': typeof PlatformPaymentsRoute
  '/production/$productionId': typeof ProductionProductionIdRoute
  '/production/batches': typeof ProductionBatchesRoute
  '/production/history': typeof ProductionHistoryRoute
  '/production/list': typeof ProductionListRoute
  '/production/new': typeof ProductionNewRoute
  '/products/$productId': typeof ProductsProductIdRouteWithChildren
  '/products/new': typeof ProductsNewRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/orders': typeof ReportsOrdersRoute
  '/reports/production': typeof ReportsProductionRoute
  '/reports/returns': typeof ReportsReturnsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/transactions': typeof ReportsTransactionsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRouteWithChildren
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/activity': typeof VendorsActivityRoute
  '/vendors/list': typeof VendorsListRoute
  '/vendors/orders': typeof VendorsOrdersRoute
  '/vendors/payments': typeof VendorsPaymentsRoute
  '/vendors/performance': typeof VendorsPerformanceRoute
  '/vendors/products': typeof VendorsProductsRoute
  '/vendors/registrations': typeof VendorsRegistrationsRoute
  '/vendors/returns': typeof VendorsReturnsRoute
  '/vendors/settlements': typeof VendorsSettlementsRoute
  '/vendors/transactions': typeof VendorsTransactionsRoute
  '/cms/': typeof CmsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/master/$kind/$itemId': typeof MasterKindItemIdRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
  '/settings/notifications/$notificationId': typeof SettingsNotificationsNotificationIdRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributes'
    | '/brands'
    | '/categories'
    | '/cms'
    | '/customers'
    | '/dashboard'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/platform'
    | '/production'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/storefront'
    | '/sub-categories'
    | '/taxes'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/cms/$contentId'
    | '/customers/$customerId'
    | '/inventory/add-stock'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/inventory/low-stock'
    | '/inventory/movements'
    | '/inventory/out-of-stock'
    | '/inventory/stock'
    | '/inventory/transfer'
    | '/master/batches'
    | '/master/commissions'
    | '/master/locations'
    | '/orders/$orderId'
    | '/platform/offers'
    | '/platform/operations'
    | '/platform/payments'
    | '/production/$productionId'
    | '/production/batches'
    | '/production/history'
    | '/production/list'
    | '/production/new'
    | '/products/$productId'
    | '/products/new'
    | '/reports/inventory'
    | '/reports/orders'
    | '/reports/production'
    | '/reports/returns'
    | '/reports/sales'
    | '/reports/settlements'
    | '/reports/transactions'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/roles'
    | '/settings/users'
    | '/vendors/$vendorId'
    | '/vendors/activity'
    | '/vendors/list'
    | '/vendors/orders'
    | '/vendors/payments'
    | '/vendors/performance'
    | '/vendors/products'
    | '/vendors/registrations'
    | '/vendors/returns'
    | '/vendors/settlements'
    | '/vendors/transactions'
    | '/cms/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/platform/'
    | '/production/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/vendors/'
    | '/master/$kind/$itemId'
    | '/products/$productId/edit'
    | '/settings/notifications/$notificationId'
    | '/products/$productId/'
    | '/settings/notifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributes'
    | '/brands'
    | '/categories'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/sales'
    | '/storefront'
    | '/sub-categories'
    | '/taxes'
    | '/units'
    | '/warehouses'
    | '/cms/$contentId'
    | '/customers/$customerId'
    | '/inventory/add-stock'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/inventory/low-stock'
    | '/inventory/movements'
    | '/inventory/out-of-stock'
    | '/inventory/stock'
    | '/inventory/transfer'
    | '/master/batches'
    | '/master/commissions'
    | '/master/locations'
    | '/orders/$orderId'
    | '/platform/offers'
    | '/platform/operations'
    | '/platform/payments'
    | '/production/$productionId'
    | '/production/batches'
    | '/production/history'
    | '/production/list'
    | '/production/new'
    | '/products/new'
    | '/reports/inventory'
    | '/reports/orders'
    | '/reports/production'
    | '/reports/returns'
    | '/reports/sales'
    | '/reports/settlements'
    | '/reports/transactions'
    | '/settings/integrations'
    | '/settings/preferences'
    | '/settings/roles'
    | '/settings/users'
    | '/vendors/$vendorId'
    | '/vendors/activity'
    | '/vendors/list'
    | '/vendors/orders'
    | '/vendors/payments'
    | '/vendors/performance'
    | '/vendors/products'
    | '/vendors/registrations'
    | '/vendors/returns'
    | '/vendors/settlements'
    | '/vendors/transactions'
    | '/cms'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/platform'
    | '/production'
    | '/products'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/master/$kind/$itemId'
    | '/products/$productId/edit'
    | '/settings/notifications/$notificationId'
    | '/products/$productId'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/attributes'
    | '/brands'
    | '/categories'
    | '/cms'
    | '/customers'
    | '/dashboard'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/orders'
    | '/platform'
    | '/production'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/storefront'
    | '/sub-categories'
    | '/taxes'
    | '/units'
    | '/vendors'
    | '/warehouses'
    | '/cms/$contentId'
    | '/customers/$customerId'
    | '/inventory/add-stock'
    | '/inventory/adjustment'
    | '/inventory/history'
    | '/inventory/low-stock'
    | '/inventory/movements'
    | '/inventory/out-of-stock'
    | '/inventory/stock'
    | '/inventory/transfer'
    | '/master/batches'
    | '/master/commissions'
    | '/master/locations'
    | '/orders/$orderId'
    | '/platform/offers'
    | '/platform/operations'
    | '/platform/payments'
    | '/production/$productionId'
    | '/production/batches'
    | '/production/history'
    | '/production/list'
    | '/production/new'
    | '/products/$productId'
    | '/products/new'
    | '/reports/inventory'
    | '/reports/orders'
    | '/reports/production'
    | '/reports/returns'
    | '/reports/sales'
    | '/reports/settlements'
    | '/reports/transactions'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/preferences'
    | '/settings/roles'
    | '/settings/users'
    | '/vendors/$vendorId'
    | '/vendors/activity'
    | '/vendors/list'
    | '/vendors/orders'
    | '/vendors/payments'
    | '/vendors/performance'
    | '/vendors/products'
    | '/vendors/registrations'
    | '/vendors/returns'
    | '/vendors/settlements'
    | '/vendors/transactions'
    | '/cms/'
    | '/customers/'
    | '/inventory/'
    | '/orders/'
    | '/platform/'
    | '/production/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/vendors/'
    | '/master/$kind/$itemId'
    | '/products/$productId/edit'
    | '/settings/notifications/$notificationId'
    | '/products/$productId/'
    | '/settings/notifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributesRoute: typeof AttributesRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  CmsRoute: typeof CmsRouteWithChildren
  CustomersRoute: typeof CustomersRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  ProductionRoute: typeof ProductionRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StorefrontRoute: typeof StorefrontRoute
  SubCategoriesRoute: typeof SubCategoriesRoute
  TaxesRoute: typeof TaxesRoute
  UnitsRoute: typeof UnitsRoute
  VendorsRoute: typeof VendorsRouteWithChildren
  WarehousesRoute: typeof WarehousesRoute
  MasterBatchesRoute: typeof MasterBatchesRoute
  MasterCommissionsRoute: typeof MasterCommissionsRoute
  MasterLocationsRoute: typeof MasterLocationsRoute
  MasterKindItemIdRoute: typeof MasterKindItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributes': {
      id: '/attributes'
      path: '/attributes'
      fullPath: '/attributes'
      preLoaderRoute: typeof AttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront': {
      id: '/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sub-categories': {
      id: '/sub-categories'
      path: '/sub-categories'
      fullPath: '/sub-categories'
      preLoaderRoute: typeof SubCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof CmsRoute
    }
    '/cms/$contentId': {
      id: '/cms/$contentId'
      path: '/$contentId'
      fullPath: '/cms/$contentId'
      preLoaderRoute: typeof CmsContentIdRouteImport
      parentRoute: typeof CmsRoute
    }
    '/customers/': {
      id: '/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/add-stock': {
      id: '/inventory/add-stock'
      path: '/add-stock'
      fullPath: '/inventory/add-stock'
      preLoaderRoute: typeof InventoryAddStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/adjustment': {
      id: '/inventory/adjustment'
      path: '/adjustment'
      fullPath: '/inventory/adjustment'
      preLoaderRoute: typeof InventoryAdjustmentRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/history': {
      id: '/inventory/history'
      path: '/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof InventoryHistoryRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/low-stock': {
      id: '/inventory/low-stock'
      path: '/low-stock'
      fullPath: '/inventory/low-stock'
      preLoaderRoute: typeof InventoryLowStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/movements': {
      id: '/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof InventoryMovementsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/out-of-stock': {
      id: '/inventory/out-of-stock'
      path: '/out-of-stock'
      fullPath: '/inventory/out-of-stock'
      preLoaderRoute: typeof InventoryOutOfStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/transfer': {
      id: '/inventory/transfer'
      path: '/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof InventoryTransferRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/master/batches': {
      id: '/master/batches'
      path: '/master/batches'
      fullPath: '/master/batches'
      preLoaderRoute: typeof MasterBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/commissions': {
      id: '/master/commissions'
      path: '/master/commissions'
      fullPath: '/master/commissions'
      preLoaderRoute: typeof MasterCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/locations': {
      id: '/master/locations'
      path: '/master/locations'
      fullPath: '/master/locations'
      preLoaderRoute: typeof MasterLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/offers': {
      id: '/platform/offers'
      path: '/offers'
      fullPath: '/platform/offers'
      preLoaderRoute: typeof PlatformOffersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/operations': {
      id: '/platform/operations'
      path: '/operations'
      fullPath: '/platform/operations'
      preLoaderRoute: typeof PlatformOperationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/payments': {
      id: '/platform/payments'
      path: '/payments'
      fullPath: '/platform/payments'
      preLoaderRoute: typeof PlatformPaymentsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/production/': {
      id: '/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/$productionId': {
      id: '/production/$productionId'
      path: '/$productionId'
      fullPath: '/production/$productionId'
      preLoaderRoute: typeof ProductionProductionIdRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/batches': {
      id: '/production/batches'
      path: '/batches'
      fullPath: '/production/batches'
      preLoaderRoute: typeof ProductionBatchesRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/history': {
      id: '/production/history'
      path: '/history'
      fullPath: '/production/history'
      preLoaderRoute: typeof ProductionHistoryRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/list': {
      id: '/production/list'
      path: '/list'
      fullPath: '/production/list'
      preLoaderRoute: typeof ProductionListRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/new': {
      id: '/production/new'
      path: '/new'
      fullPath: '/production/new'
      preLoaderRoute: typeof ProductionNewRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/orders': {
      id: '/reports/orders'
      path: '/orders'
      fullPath: '/reports/orders'
      preLoaderRoute: typeof ReportsOrdersRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/production': {
      id: '/reports/production'
      path: '/production'
      fullPath: '/reports/production'
      preLoaderRoute: typeof ReportsProductionRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/returns': {
      id: '/reports/returns'
      path: '/returns'
      fullPath: '/reports/returns'
      preLoaderRoute: typeof ReportsReturnsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/settlements': {
      id: '/reports/settlements'
      path: '/settlements'
      fullPath: '/reports/settlements'
      preLoaderRoute: typeof ReportsSettlementsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/transactions': {
      id: '/reports/transactions'
      path: '/transactions'
      fullPath: '/reports/transactions'
      preLoaderRoute: typeof ReportsTransactionsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/activity': {
      id: '/vendors/activity'
      path: '/activity'
      fullPath: '/vendors/activity'
      preLoaderRoute: typeof VendorsActivityRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/list': {
      id: '/vendors/list'
      path: '/list'
      fullPath: '/vendors/list'
      preLoaderRoute: typeof VendorsListRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/orders': {
      id: '/vendors/orders'
      path: '/orders'
      fullPath: '/vendors/orders'
      preLoaderRoute: typeof VendorsOrdersRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/payments': {
      id: '/vendors/payments'
      path: '/payments'
      fullPath: '/vendors/payments'
      preLoaderRoute: typeof VendorsPaymentsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/performance': {
      id: '/vendors/performance'
      path: '/performance'
      fullPath: '/vendors/performance'
      preLoaderRoute: typeof VendorsPerformanceRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/products': {
      id: '/vendors/products'
      path: '/products'
      fullPath: '/vendors/products'
      preLoaderRoute: typeof VendorsProductsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/registrations': {
      id: '/vendors/registrations'
      path: '/registrations'
      fullPath: '/vendors/registrations'
      preLoaderRoute: typeof VendorsRegistrationsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/returns': {
      id: '/vendors/returns'
      path: '/returns'
      fullPath: '/vendors/returns'
      preLoaderRoute: typeof VendorsReturnsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/settlements': {
      id: '/vendors/settlements'
      path: '/settlements'
      fullPath: '/vendors/settlements'
      preLoaderRoute: typeof VendorsSettlementsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/vendors/transactions': {
      id: '/vendors/transactions'
      path: '/transactions'
      fullPath: '/vendors/transactions'
      preLoaderRoute: typeof VendorsTransactionsRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/master/$kind/$itemId': {
      id: '/master/$kind/$itemId'
      path: '/master/$kind/$itemId'
      fullPath: '/master/$kind/$itemId'
      preLoaderRoute: typeof MasterKindItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof ProductsProductIdRoute
    }
    '/products/$productId/edit': {
      id: '/products/$productId/edit'
      path: '/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof ProductsProductIdRoute
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof SettingsNotificationsIndexRouteImport
      parentRoute: typeof SettingsNotificationsRoute
    }
    '/settings/notifications/$notificationId': {
      id: '/settings/notifications/$notificationId'
      path: '/$notificationId'
      fullPath: '/settings/notifications/$notificationId'
      preLoaderRoute: typeof SettingsNotificationsNotificationIdRouteImport
      parentRoute: typeof SettingsNotificationsRoute
    }
  }
}

interface CmsRouteChildren {
  CmsContentIdRoute: typeof CmsContentIdRoute
  CmsIndexRoute: typeof CmsIndexRoute
}

const CmsRouteChildren: CmsRouteChildren = {
  CmsContentIdRoute: CmsContentIdRoute,
  CmsIndexRoute: CmsIndexRoute,
}

const CmsRouteWithChildren = CmsRoute._addFileChildren(CmsRouteChildren)

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InventoryRouteChildren {
  InventoryAddStockRoute: typeof InventoryAddStockRoute
  InventoryAdjustmentRoute: typeof InventoryAdjustmentRoute
  InventoryHistoryRoute: typeof InventoryHistoryRoute
  InventoryLowStockRoute: typeof InventoryLowStockRoute
  InventoryMovementsRoute: typeof InventoryMovementsRoute
  InventoryOutOfStockRoute: typeof InventoryOutOfStockRoute
  InventoryStockRoute: typeof InventoryStockRoute
  InventoryTransferRoute: typeof InventoryTransferRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryAddStockRoute: InventoryAddStockRoute,
  InventoryAdjustmentRoute: InventoryAdjustmentRoute,
  InventoryHistoryRoute: InventoryHistoryRoute,
  InventoryLowStockRoute: InventoryLowStockRoute,
  InventoryMovementsRoute: InventoryMovementsRoute,
  InventoryOutOfStockRoute: InventoryOutOfStockRoute,
  InventoryStockRoute: InventoryStockRoute,
  InventoryTransferRoute: InventoryTransferRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface PlatformRouteChildren {
  PlatformOffersRoute: typeof PlatformOffersRoute
  PlatformOperationsRoute: typeof PlatformOperationsRoute
  PlatformPaymentsRoute: typeof PlatformPaymentsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformOffersRoute: PlatformOffersRoute,
  PlatformOperationsRoute: PlatformOperationsRoute,
  PlatformPaymentsRoute: PlatformPaymentsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ProductionRouteChildren {
  ProductionProductionIdRoute: typeof ProductionProductionIdRoute
  ProductionBatchesRoute: typeof ProductionBatchesRoute
  ProductionHistoryRoute: typeof ProductionHistoryRoute
  ProductionListRoute: typeof ProductionListRoute
  ProductionNewRoute: typeof ProductionNewRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionProductionIdRoute: ProductionProductionIdRoute,
  ProductionBatchesRoute: ProductionBatchesRoute,
  ProductionHistoryRoute: ProductionHistoryRoute,
  ProductionListRoute: ProductionListRoute,
  ProductionNewRoute: ProductionNewRoute,
  ProductionIndexRoute: ProductionIndexRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

interface ProductsProductIdRouteChildren {
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

const ProductsProductIdRouteChildren: ProductsProductIdRouteChildren = {
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}

const ProductsProductIdRouteWithChildren =
  ProductsProductIdRoute._addFileChildren(ProductsProductIdRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRouteWithChildren
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRouteWithChildren,
  ProductsNewRoute: ProductsNewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsOrdersRoute: typeof ReportsOrdersRoute
  ReportsProductionRoute: typeof ReportsProductionRoute
  ReportsReturnsRoute: typeof ReportsReturnsRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsSettlementsRoute: typeof ReportsSettlementsRoute
  ReportsTransactionsRoute: typeof ReportsTransactionsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsOrdersRoute: ReportsOrdersRoute,
  ReportsProductionRoute: ReportsProductionRoute,
  ReportsReturnsRoute: ReportsReturnsRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsSettlementsRoute: ReportsSettlementsRoute,
  ReportsTransactionsRoute: ReportsTransactionsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SettingsNotificationsRouteChildren {
  SettingsNotificationsNotificationIdRoute: typeof SettingsNotificationsNotificationIdRoute
  SettingsNotificationsIndexRoute: typeof SettingsNotificationsIndexRoute
}

const SettingsNotificationsRouteChildren: SettingsNotificationsRouteChildren = {
  SettingsNotificationsNotificationIdRoute:
    SettingsNotificationsNotificationIdRoute,
  SettingsNotificationsIndexRoute: SettingsNotificationsIndexRoute,
}

const SettingsNotificationsRouteWithChildren =
  SettingsNotificationsRoute._addFileChildren(
    SettingsNotificationsRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRouteWithChildren
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRouteWithChildren,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface VendorsRouteChildren {
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  VendorsActivityRoute: typeof VendorsActivityRoute
  VendorsListRoute: typeof VendorsListRoute
  VendorsOrdersRoute: typeof VendorsOrdersRoute
  VendorsPaymentsRoute: typeof VendorsPaymentsRoute
  VendorsPerformanceRoute: typeof VendorsPerformanceRoute
  VendorsProductsRoute: typeof VendorsProductsRoute
  VendorsRegistrationsRoute: typeof VendorsRegistrationsRoute
  VendorsReturnsRoute: typeof VendorsReturnsRoute
  VendorsSettlementsRoute: typeof VendorsSettlementsRoute
  VendorsTransactionsRoute: typeof VendorsTransactionsRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  VendorsActivityRoute: VendorsActivityRoute,
  VendorsListRoute: VendorsListRoute,
  VendorsOrdersRoute: VendorsOrdersRoute,
  VendorsPaymentsRoute: VendorsPaymentsRoute,
  VendorsPerformanceRoute: VendorsPerformanceRoute,
  VendorsProductsRoute: VendorsProductsRoute,
  VendorsRegistrationsRoute: VendorsRegistrationsRoute,
  VendorsReturnsRoute: VendorsReturnsRoute,
  VendorsSettlementsRoute: VendorsSettlementsRoute,
  VendorsTransactionsRoute: VendorsTransactionsRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributesRoute: AttributesRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  CmsRoute: CmsRouteWithChildren,
  CustomersRoute: CustomersRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  ProductionRoute: ProductionRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StorefrontRoute: StorefrontRoute,
  SubCategoriesRoute: SubCategoriesRoute,
  TaxesRoute: TaxesRoute,
  UnitsRoute: UnitsRoute,
  VendorsRoute: VendorsRouteWithChildren,
  WarehousesRoute: WarehousesRoute,
  MasterBatchesRoute: MasterBatchesRoute,
  MasterCommissionsRoute: MasterCommissionsRoute,
  MasterLocationsRoute: MasterLocationsRoute,
  MasterKindItemIdRoute: MasterKindItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
