export const orders = [
  {
    id: "BLM-10482",
    customer: "Aarav Mehta",
    date: "18 Sep, 10:42",
    total: "₹8,298",
    payment: "Paid",
    status: "Processing",
    items: "2 items",
    email: "aarav@example.com",
    address: "Bandra West, Mumbai",
    products: ["Wireless Headphones", "Organic Cotton T-Shirt"],
  },
  {
    id: "BLM-10481",
    customer: "Meera Iyer",
    date: "18 Sep, 09:18",
    total: "₹3,499",
    payment: "Paid",
    status: "Shipped",
    items: "1 item",
    email: "meera@example.com",
    address: "Indiranagar, Bengaluru",
    products: ["Arc Table Lamp"],
  },
  {
    id: "BLM-10480",
    customer: "Kabir Shah",
    date: "17 Sep, 18:04",
    total: "₹6,999",
    payment: "Paid",
    status: "Delivered",
    items: "1 item",
    email: "kabir@example.com",
    address: "Vasant Kunj, New Delhi",
    products: ["Wireless Headphones"],
  },
  {
    id: "BLM-10479",
    customer: "Ananya Rao",
    date: "17 Sep, 15:36",
    total: "₹2,198",
    payment: "Pending",
    status: "Processing",
    items: "3 items",
    email: "ananya@example.com",
    address: "Jubilee Hills, Hyderabad",
    products: ["Vitamin C Face Serum", "Organic Cotton T-Shirt"],
  },
  {
    id: "BLM-10478",
    customer: "Rohan Kapoor",
    date: "17 Sep, 12:11",
    total: "₹4,299",
    payment: "Refunded",
    status: "Returned",
    items: "1 item",
    email: "rohan@example.com",
    address: "Koregaon Park, Pune",
    products: ["Everyday Running Sneakers"],
  },
  {
    id: "BLM-10477",
    customer: "Diya Nair",
    date: "16 Sep, 17:45",
    total: "₹10,198",
    payment: "Paid",
    status: "Delivered",
    items: "2 items",
    email: "diya@example.com",
    address: "Panampilly Nagar, Kochi",
    products: ["Ceramic Cookware Set", "Insulated Water Bottle"],
  },
] as const;

export const customers = [
  {
    id: "CUS-2048",
    name: "Aarav Mehta",
    email: "aarav@example.com",
    phone: "+91 98765 41082",
    orders: 18,
    spent: "₹84,620",
    segment: "VIP",
    joined: "12 Jan 2025",
    city: "Mumbai",
    status: "Active",
  },
  {
    id: "CUS-2047",
    name: "Meera Iyer",
    email: "meera@example.com",
    phone: "+91 98670 33891",
    orders: 12,
    spent: "₹52,340",
    segment: "Returning",
    joined: "4 Mar 2025",
    city: "Bengaluru",
    status: "Active",
  },
  {
    id: "CUS-2046",
    name: "Kabir Shah",
    email: "kabir@example.com",
    phone: "+91 99204 67018",
    orders: 8,
    spent: "₹31,875",
    segment: "Returning",
    joined: "18 Jun 2025",
    city: "New Delhi",
    status: "Active",
  },
  {
    id: "CUS-2045",
    name: "Ananya Rao",
    email: "ananya@example.com",
    phone: "+91 98490 42136",
    orders: 3,
    spent: "₹8,970",
    segment: "New",
    joined: "2 Sep 2026",
    city: "Hyderabad",
    status: "Active",
  },
  {
    id: "CUS-2044",
    name: "Rohan Kapoor",
    email: "rohan@example.com",
    phone: "+91 98231 61547",
    orders: 6,
    spent: "₹19,260",
    segment: "At risk",
    joined: "29 Nov 2025",
    city: "Pune",
    status: "Inactive",
  },
  {
    id: "CUS-2043",
    name: "Diya Nair",
    email: "diya@example.com",
    phone: "+91 98951 73420",
    orders: 14,
    spent: "₹68,110",
    segment: "VIP",
    joined: "9 Feb 2025",
    city: "Kochi",
    status: "Active",
  },
] as const;

export const cmsEntries = [
  {
    id: "home-banner",
    title: "Monsoon Essentials",
    type: "Homepage banner",
    status: "Published",
    author: "Priya Shah",
    updated: "Today, 09:24",
    placement: "Homepage · Hero",
    summary: "Seasonal campaign featuring weather-ready apparel and accessories.",
  },
  {
    id: "summer-style",
    title: "The Summer Style Edit",
    type: "Editorial page",
    status: "Published",
    author: "Alex Morgan",
    updated: "Yesterday",
    placement: "Discover · Featured",
    summary: "A curated editorial collection of lightweight summer essentials.",
  },
  {
    id: "delivery-policy",
    title: "Shipping & Delivery",
    type: "Policy page",
    status: "Published",
    author: "Neha Singh",
    updated: "14 Sep 2026",
    placement: "Footer · Help",
    summary: "Delivery timeframes, shipping fees, and order tracking information.",
  },
  {
    id: "festive-sale",
    title: "Festive Sale Preview",
    type: "Campaign",
    status: "Draft",
    author: "Priya Shah",
    updated: "12 Sep 2026",
    placement: "Scheduled",
    summary: "Early creative and promotional copy for the upcoming festive event.",
  },
  {
    id: "about-bloom",
    title: "About Bloom",
    type: "Content page",
    status: "Published",
    author: "Alex Morgan",
    updated: "8 Sep 2026",
    placement: "Footer · Company",
    summary: "Bloom's brand story, values, and commitment to thoughtful commerce.",
  },
] as const;
